### ISSUE TITLE
Building with GCC 7 fails with -Werror=implicit-fallthrough

### ISSUE THREAD

**Issue by dclenz** [3343/edge#23]
Building from Master with GCC 7 and later fails due to a combination of -Wextra and -Werror.  Since GCC 7, -Wextra emits the warning -Wimplicit-fallthrough= when a switch-case block is missing a "break" at the end of each case.

The submodule pugixml seems to have this issue, GCC apparently takes issue with a switch block, sends out the warning, and the terminates due to -Werror.

This can be suppressed by compiling with the flag -Wimplicit-fallthrough=0.

**Comment by breuera** [comment]
The changes are now merged.
